### ISSUE TITLE
pyfnnd mutating input fluorescence trace

### ISSUE THREAD

**Issue by amyjc** [alimuldal/PyFNND#4]
I'm testing out pyfnnd on a new dataset and ran into a problem I hadn't noticed before. 

pyfnnd seems to be mutating the fluorescence trace I pass it. Specifically, the trace gets scaled down by many orders of magnitude when I run pyfnnd.deconvolve. 

![image](https://user-images.githubusercontent.com/12806221/33307704-5e062b64-d3cc-11e7-8cbe-2e72a8dcc52b.png)

Code below, note that when I plot trace after i call deconvolve, trace is scaled down from the original traces it was copied from. 

`trace = np.copy(traces[1, :])

n_best, C_best, LL, theta_best = deconvolve(trace, c0 = trace, dt = 0.02)

plt.figure(figsize = [10, 5])

plt.subplot(311)
plt.plot(n_best[0:5000])
plt.ylabel("n best")

plt.subplot(312)
plt.ylabel("trace that was run through pyfnnd")
plt.plot(trace[0:5000])

plt.subplot(313)
plt.plot(traces[1, 0:5000])
plt.ylabel("original trace")
'

**Comment by alimuldal** [comment]
I see - you're passing `c0=trace`, and `c0` is being modified in place. That's a bug - I'll update the code to force a copy of `c0`. However it's probably a bad idea to pass a raw fluorescence trace as the initial estimate of the calcium concentration. You want `c0` to be initialized in a way that avoids spike probabilities that are too close to zero or negative, otherwise you could fail on the first iteration or get caught in local minimum. This could happen, for example, if `c0` is noisy or badly scaled. By default we generate a `c0` that yields uniform positive spike probabilities on the first pass: https://github.com/alimuldal/PyFNND/blob/master/pyfnnd/_fnndeconv.py#L196.
